I'm sorry, but an uncaught exception occurred.

While loading <renpy.display.im.Image object ('gui/button/quick_hover_background.png') at 0x1066aab80>:
  File "game/chapterone.rpy", line 169, in script
    call screen outfits2
ScriptError: could not find label 'scene black bg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/main.py", line 652, in main
    run(restart)
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/execution.py", line 958, in run_context
    context.run()
  File "game/chapterone.rpy", line 169, in script
    call screen outfits2
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'scene black bg'.

macOS-15.0.1-arm64-arm-64bit arm64
Ren'