I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/movienight.rpy", line 95, in script
    Naida "Hey, more beanbag space for me! I’m not complaining!"
Exception: Sayer 'Naida' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/movienight.rpy", line 95, in script
    Naida "Hey, more beanbag space for me! I’m not complaining!"
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 2560, in execute
    Say.execute(self)
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Naida' is not defined.

macOS-13.5-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Chic Boutique 1.0
Mon Jun  2 16:10:20 2025
