I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapterone.rpy", line 343, in script
    call screen outfits_ui2
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "renpy/common/00action_control.rpy", line 131, in __call__
    renpy.show_screen(self.screen, *self.args, **self.kwargs)
Exception: Screen shoe7 is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapterone.rpy", line 343, in script
    call screen outfits_ui2
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 1971, in execute
    self.call("execute")
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/exports.py", line 3420, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "/Applications/renpy-8.2.3-sdk/renpy/ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/core.py", line 2166, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "/Applications/renpy-8.2.3-sdk/renpy/display/core.py", line 2688, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Applications/renpy-8.2.3-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/displayable.py", line 431, in visit_all
    d.visit_all(callback, seen)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/screen.py", line 480, in visit_all
    callback(self)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/core.py", line 2688, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "/Applications/renpy-8.2.3-sdk/renpy/display/screen.py", line 491, in per_interact
    self.update()
  File "/Applications/renpy-8.2.3-sdk/renpy/display/screen.py", line 726, in update
    i.set_transform_event(self.current_transform_event)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/behavior.py", line 2757, in set_transform_event
    rv = run(self.action)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/behavior.py", line 388, in run
    new_rv = run(i, *args, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/behavior.py", line 395, in run
    return action(*args, **kwargs)
  File "renpy/common/00action_control.rpy", line 131, in __call__
    renpy.show_screen(self.screen, *self.args, **self.kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/display/screen.py", line 1322, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen shoe7 is not known.


macOS-13.5-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Chic Boutique 1.0
Fri May 30 08:39:14 2025
