I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologue.rpy", line 226, in script
    init python:
  File "game/prologue.rpy", line 269, in <module>
    x("Assets/Shoe_1_%s.png", "Assets/Shoe_1_%s.png",   "shoe",   "shoe0", 0,   0, 200),
NameError: name 'x' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologue.rpy", line 226, in script
    init python:
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Applications/renpy-8.2.3-sdk/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/prologue.rpy", line 269, in <module>
    x("Assets/Shoe_1_%s.png", "Assets/Shoe_1_%s.png",   "shoe",   "shoe0", 0,   0, 200),
NameError: name 'x' is not defined

macOS-13.5-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Chic Boutique 1.0
Tue May 27 01:14:48 2025
